### Data Exploration
 In this notebook, i will examine the dataset structure, date ranges, missing values, duplicate records, and key variables of both datasets to assess their suitability for analysis.

In [93]:
import pandas as pd
import matplotlib as plt
import seaborn as sns

# load data
billboard = pd.read_csv("/Users/apeksha/Desktop/Bootcamp/Final Project/data/raw/hot100.csv")
tiktok_trends = pd.read_csv("/Users/apeksha/Desktop/Bootcamp/Final Project/data/raw/trending_music.csv")

/var/folders/s0/63z2rhps419c6k0sff6vdwjc0000gn/T/ipykernel_11360/2117845140.py:6: DtypeWarning: Columns (0: Weeks in Charts) have mixed types. Specify dtype option on import or set low_memory=False.
  billboard = pd.read_csv("/Users/apeksha/Desktop/Bootcamp/Final Project/data/raw/hot100.csv")

#### Billboard dataset exploration

In [59]:
billboard.shape, billboard.size

((355758, 8), 2846064)

In [60]:
billboard.columns.tolist()

['Date',
 'Song',
 'Artist',
 'Rank',
 'Last Week',
 'Peak Position',
 'Weeks in Charts',
 'Image URL']

In [61]:
billboard.info()

<class 'pandas.DataFrame'>
RangeIndex: 355758 entries, 0 to 355757
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Date             355758 non-null  str
 1   Song             355758 non-null  str
 2   Artist           355758 non-null  str
 3   Rank             355758 non-null  int64
 4   Last Week        355758 non-null  str
 5   Peak Position    355758 non-null  int64
 6   Weeks in Charts  355758 non-null  object
 7   Image URL        231543 non-null  str
dtypes: int64(2), object(1), str(5)
memory usage: 53.8+ MB

In [62]:
# convert date to a proper datetime format
billboard["Date"] = pd.to_datetime(billboard["Date"], errors="coerce")

print("Earliest date:", billboard["Date"].min())
print("Latest date:", billboard["Date"].max())

print("\nRanking statistics:")
display(billboard[["Rank", "Peak Position", "Weeks in Charts"]].describe())

Earliest date: 1958-07-30 00:00:00
Latest date: 2026-09-30 00:00:00

Ranking statistics:

                Rank  Peak Position
count  355758.000000  355758.000000
mean       50.501074      40.374651
std        28.866355      29.295724
min         1.000000       1.000000
25%        26.000000      13.000000
50%        51.000000      37.000000
75%        76.000000      65.000000
max       100.000000     100.000000

In [63]:
billboard.info()

<class 'pandas.DataFrame'>
RangeIndex: 355758 entries, 0 to 355757
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Date             355758 non-null  datetime64[us]
 1   Song             355758 non-null  str
 2   Artist           355758 non-null  str
 3   Rank             355758 non-null  int64
 4   Last Week        355758 non-null  str
 5   Peak Position    355758 non-null  int64
 6   Weeks in Charts  355758 non-null  object
 7   Image URL        231543 non-null  str
dtypes: datetime64[us](1), int64(2), object(1), str(4)
memory usage: 50.4+ MB

In [64]:
billboard.duplicated().sum()

np.int64(0)

In [65]:
# missing values
print("Missing values per column:")
display(billboard.isnull().sum().to_frame("missing_values"))

# duplicate rows
print("Exact duplicate rows:", billboard.duplicated().sum())

Missing values per column:

                 missing_values
Date                          0
Song                          0
Artist                        0
Rank                          0
Last Week                     0
Peak Position                 0
Weeks in Charts               0
Image URL                124215

Exact duplicate rows: 0

In [66]:
billboard.head()

,Date,Song,Artist,Rank,Last Week,Peak Position,Weeks in Charts,Image URL
0,1958-07-30,Poor Little Fool,Ricky Nelson,1,-,1,1,NaN
1,1958-07-30,Patricia,Perez Prado And His Orchestra,2,-,2,1,NaN
2,1958-07-30,Splish Splash,Bobby Darin,3,-,3,1,NaN
3,1958-07-30,Hard Headed Woman,Elvis Presley With The Jordanaires,4,-,4,1,https://charts-static.billboard.com/img/1958/0...
4,1958-07-30,When,Kalin Twins,5,-,5,1,NaN

##### investigating "last week"

In [67]:
billboard["Last Week"].value_counts(dropna=False).head(20)

Last Week
-     36391
5      3553
2      3552
8      3552
7      3552
1      3551
4      3550
6      3550
3      3549
10     3549
9      3548
12     3547
14     3547
17     3547
11     3544
15     3543
13     3542
18     3541
19     3539
16     3537
Name: count, dtype: int64

In [68]:
last_week_numeric = pd.to_numeric(billboard["Last Week"], errors="coerce")

print("Non-numeric values:")
print(billboard.loc[last_week_numeric.isna(), "Last Week"].value_counts(dropna=False).head(20))

print("Number of non-numeric values:", last_week_numeric.isna().sum())

Non-numeric values:
Last Week
-    36391
Name: count, dtype: int64
Number of non-numeric values: 36391

In [69]:
billboard["Weeks in Charts"].value_counts(dropna=False).head(20)

Weeks in Charts
1     29348
2     26851
3     25195
4     23780
5     22399
6     20957
7     19391
8     17812
9     16207
10    14792
11    13523
12    12250
13    11129
14    10041
15     9008
16     8073
17     7209
18     6500
19     5811
20     5227
Name: count, dtype: int64

In [70]:
weeks_numeric = pd.to_numeric(billboard["Weeks in Charts"], errors="coerce")

print("Non-numeric values:")
print(billboard.loc[weeks_numeric.isna(), "Weeks in Charts"].value_counts(dropna=False).head(20))

print("Number of non-numeric values:", weeks_numeric.isna().sum())

Non-numeric values:
Weeks in Charts
-    300
Name: count, dtype: int64
Number of non-numeric values: 300

In [71]:
print("Minimum rank:", billboard["Rank"].min())
print("Maximum rank:", billboard["Rank"].max())
print("Unique ranks:", billboard["Rank"].nunique())

print("\nFrequency of each rank:")
print(billboard["Rank"].value_counts().sort_index())

Minimum rank: 1
Maximum rank: 100
Unique ranks: 100

Frequency of each rank:
Rank
1      3558
2      3558
3      3558
4      3558
5      3558
       ...
96     3558
97     3558
98     3558
99     3557
100    3558
Name: count, Length: 100, dtype: int64

In [72]:
print("Earliest date:", billboard["Date"].min())
print("Latest date:", billboard["Date"].max())

print("Number of unique chart dates:", billboard["Date"].nunique())

print("\nNumber of rows per chart date:")
print(billboard.groupby("Date").size().describe())

Earliest date: 1958-07-30 00:00:00
Latest date: 2026-09-30 00:00:00
Number of unique chart dates: 3558

Number of rows per chart date:
count    3558.000000
mean       99.988196
std         0.127148
min        97.000000
25%       100.000000
50%       100.000000
75%       100.000000
max       100.000000
dtype: float64

In [73]:
# display records with non-numeric Weeks in Charts
unusual_weeks = billboard[
    pd.to_numeric(
        billboard["Weeks in Charts"], errors="coerce"
    ).isna()
]

display(unusual_weeks.head(20))

,Date,Song,Artist,Rank,Last Week,Peak Position,Weeks in Charts,Image URL
355458,2026-09-16,Choosin' Texas,Ella Langley,1,1,1,-,https://charts-static.billboard.com/img/2025/1...
355459,2026-09-16,Boston,Stella Lefty,2,2,2,-,https://charts-static.billboard.com/img/2026/0...
355460,2026-09-16,"""I Knew It, I Knew You""",Taylor Swift,3,3,1,-,https://charts-static.billboard.com/img/2026/0...
355461,2026-09-16,Been By Now,Morgan Wallen,4,5,2,-,https://charts-static.billboard.com/img/2026/0...
355462,2026-09-16,Hate That I Made You Love Me,Ariana Grande,5,4,1,-,https://charts-static.billboard.com/img/2026/0...
355463,2026-09-16,Dracula,Tame Impala & JENNIE,6,6,5,-,https://charts-static.billboard.com/img/2025/1...
355464,2026-09-16,So Easy (To Fall In Love),Olivia Dean,7,7,5,-,https://charts-static.billboard.com/img/2022/0...
355465,2026-09-16,Man I Need,Olivia Dean,8,8,2,-,https://charts-static.billboard.com/img/2025/0...
355466,2026-09-16,Be Her,Ella Langley,9,10,2,-,https://charts-static.billboard.com/img/2023/0...
355467,2026-09-16,BbY WOW,Karol G With Judeline & rusowsky,10,16,10,-,https://charts-static.billboard.com/img/2026/0...
355468,2026-09-16,Risk It All,Bruno Mars,11,9,4,-,https://charts-static.billboard.com/img/2010/0...
355469,2026-09-16,Stupid Song,Olivia Rodrigo,12,12,3,-,https://charts-static.billboard.com/img/2019/1...
355470,2026-09-16,Midnight Sun,Zara Larsson,13,15,13,-,https://charts-static.billboard.com/img/2025/0...
355471,2026-09-16,I Can't Love You Anymore,Ella Langley & Morgan Wallen,14,11,4,-,https://charts-static.billboard.com/img/2026/0...
355472,2026-09-16,I Just Might,Bruno Mars,15,14,1,-,https://charts-static.billboard.com/img/2010/0...
355473,2026-09-16,Drop Dead,Olivia Rodrigo,16,13,1,-,https://charts-static.billboard.com/img/2026/0...
355474,2026-09-16,Be By You,Luke Combs,17,18,12,-,https://charts-static.billboard.com/img/2015/0...
355475,2026-09-16,Janice STFU,Drake,18,17,1,-,https://charts-static.billboard.com/img/2009/0...
355476,2026-09-16,Earrings,Malcolm Todd,19,21,19,-,https://charts-static.billboard.com/img/2024/1...
355477,2026-09-16,Babydoll,Dominic Fike,20,20,16,-,https://charts-static.billboard.com/img/2024/0...

In [74]:
unusual_weeks = billboard[billboard["Weeks in Charts"].astype(str) == "-"]

print("Number of records:", len(unusual_weeks))
print("Dates covered:")
print(unusual_weeks["Date"].value_counts().sort_index())

display(unusual_weeks[["Date", "Song", "Artist", "Rank","Last Week", "Weeks in Charts"]].head(10))

Number of records: 300
Dates covered:
Date
2026-09-16    100
2026-09-23    100
2026-09-30    100
Name: count, dtype: int64

,Date,Song,Artist,Rank,Last Week,Weeks in Charts
355458,2026-09-16,Choosin' Texas,Ella Langley,1,1,-
355459,2026-09-16,Boston,Stella Lefty,2,2,-
355460,2026-09-16,"""I Knew It, I Knew You""",Taylor Swift,3,3,-
355461,2026-09-16,Been By Now,Morgan Wallen,4,5,-
355462,2026-09-16,Hate That I Made You Love Me,Ariana Grande,5,4,-
355463,2026-09-16,Dracula,Tame Impala & JENNIE,6,6,-
355464,2026-09-16,So Easy (To Fall In Love),Olivia Dean,7,7,-
355465,2026-09-16,Man I Need,Olivia Dean,8,8,-
355466,2026-09-16,Be Her,Ella Langley,9,10,-
355467,2026-09-16,BbY WOW,Karol G With Judeline & rusowsky,10,16,-

##### Tiktok dataset exploration

In [75]:
tiktok_trends.head()

,date,window_days,rank,song_id,clip_id,music_title,music_author,duration,rank_diff,rank_diff_type,rank_diff_label,is_commercial_music_library,is_promoted,country_code
0,2024-05-23,7,1,6844194558532651010,6844194559707088898,たぶん,YOASOBI,60,0.0,2,same,0,0,US
1,2024-05-23,7,2,7345183002882902018,7345176648368752641,Close,Cayo,60,NaN,4,new_to_top100,0,0,US
2,2024-05-23,7,3,6732292584862910465,6930510459246217217,Ghost Town,Kanye West,60,NaN,4,new_to_top100,0,0,US
3,2024-05-23,7,4,6995755961386272770,6995755962208356354,In My Mind,Lyn Lapid,60,NaN,4,new_to_top100,0,0,US
4,2024-05-23,7,5,6705086730946480129,6705026294012184578,Good Old Days,Macklemore & Kesha,60,NaN,4,new_to_top100,0,0,US

In [76]:
tiktok_trends.shape, tiktok_trends.size

((104886, 14), 1468404)

In [77]:
tiktok_trends.columns.tolist()

['date',
 'window_days',
 'rank',
 'song_id',
 'clip_id',
 'music_title',
 'music_author',
 'duration',
 'rank_diff',
 'rank_diff_type',
 'rank_diff_label',
 'is_commercial_music_library',
 'is_promoted',
 'country_code']

In [78]:
tiktok_trends.info()

<class 'pandas.DataFrame'>
RangeIndex: 104886 entries, 0 to 104885
Data columns (total 14 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   date                         104886 non-null  str
 1   window_days                  104886 non-null  int64
 2   rank                         104886 non-null  int64
 3   song_id                      104886 non-null  int64
 4   clip_id                      104886 non-null  int64
 5   music_title                  104886 non-null  str
 6   music_author                 104886 non-null  str
 7   duration                     104886 non-null  int64
 8   rank_diff                    77645 non-null   float64
 9   rank_diff_type               104886 non-null  int64
 10  rank_diff_label              104886 non-null  str
 11  is_commercial_music_library  104886 non-null  int64
 12  is_promoted                  104886 non-null  int64
 13  country_code                 104886 non-null  str
dtypes: float64(1), int64(8), str(5)
memory usage: 16.3 MB

In [79]:
# convert date to a proper datetime format
tiktok_trends["date"] = pd.to_datetime(tiktok_trends["date"], errors="coerce")

print("Earliest date:", tiktok_trends["date"].min())
print("Latest date:", tiktok_trends["date"].max())

Earliest date: 2024-05-23 00:00:00
Latest date: 2025-07-09 00:00:00

In [80]:
tiktok_trends.info()

<class 'pandas.DataFrame'>
RangeIndex: 104886 entries, 0 to 104885
Data columns (total 14 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   date                         104886 non-null  datetime64[us]
 1   window_days                  104886 non-null  int64
 2   rank                         104886 non-null  int64
 3   song_id                      104886 non-null  int64
 4   clip_id                      104886 non-null  int64
 5   music_title                  104886 non-null  str
 6   music_author                 104886 non-null  str
 7   duration                     104886 non-null  int64
 8   rank_diff                    77645 non-null   float64
 9   rank_diff_type               104886 non-null  int64
 10  rank_diff_label              104886 non-null  str
 11  is_commercial_music_library  104886 non-null  int64
 12  is_promoted                  104886 non-null  int64
 13  country_code                 104886 non-null  str
dtypes: datetime64[us](1), float64(1), int64(8), str(4)
memory usage: 15.3 MB

In [81]:
# missing values
print("Missing values per column:")
display(tiktok_trends.isnull().sum().to_frame("missing_values"))

# duplicate rows
print("Exact duplicate rows:", tiktok_trends.duplicated().sum())

Missing values per column:

                             missing_values
date                                      0
window_days                               0
rank                                      0
song_id                                   0
clip_id                                   0
music_title                               0
music_author                              0
duration                                  0
rank_diff                             27241
rank_diff_type                            0
rank_diff_label                           0
is_commercial_music_library               0
is_promoted                               0
country_code                              0

Exact duplicate rows: 0

In [82]:
tiktok_trends["window_days"].value_counts(dropna=False)

window_days
7      35602
30     35487
120    33797
Name: count, dtype: int64

In [83]:
tiktok_trends["country_code"].value_counts(dropna=False)

country_code
US    104886
Name: count, dtype: int64

In [84]:
# exploring rank columns and the datas in it
print("Minimum rank:", tiktok_trends["rank"].min())
print("Maximum rank:", tiktok_trends["rank"].max())
print("Unique ranks:", tiktok_trends["rank"].nunique())

print("\nFrequency of each rank:")
print(tiktok_trends["rank"].value_counts().sort_index())

Minimum rank: 1
Maximum rank: 100
Unique ranks: 100

Frequency of each rank:
rank
1      1074
2      1074
3      1064
4      1073
5      1068
       ...
96     1058
97     1053
98     1055
99     1057
100    1058
Name: count, Length: 100, dtype: int64

In [85]:
# exploring unoque songs, clips and freq appearing songs
print("Unique Song id:", tiktok_trends["song_id"].nunique())
print("Unique clip id:", tiktok_trends["clip_id"].nunique())
print("Unique song title:", tiktok_trends["music_title"].nunique())

print("\nFrequently appearing songs:")
print(tiktok_trends["music_title"].value_counts().head(10))

Unique Song id: 11157
Unique clip id: 11403
Unique song title: 10467

Frequently appearing songs:
music_title
Aesthetic                                390
Monkeys Spinning Monkeys                 384
Love You So                              383
Stuck In The Middle                      383
snowfall                                 382
Funny                                    369
Pretty (Sped Up)                         358
Suspense, horror, piano and music box    358
Boundless Worship                        353
i was only temporary                     332
Name: count, dtype: int64

In [86]:
# explore rank_diff to understand missing values
print(tiktok_trends["rank_diff_label"].value_counts(dropna=False))

rank_diff_label
increase         38039
new_to_top100    27241
same             20269
decrease         19337
Name: count, dtype: int64

In [87]:
print(tiktok_trends["rank_diff_type"].value_counts(dropna=False))

rank_diff_type
1    38039
4    27241
2    20269
3    19337
Name: count, dtype: int64

In [88]:
# inspect records with missing rank_diff
missing_rank_diff = tiktok_trends[tiktok_trends["rank_diff"].isna()]

print("Rows with missing rank_diff:", len(missing_rank_diff))

display(
    missing_rank_diff[
        [
            "date",
            "window_days",
            "rank",
            "music_title",
            "music_author",
            "rank_diff",
            "rank_diff_type",
            "rank_diff_label",
        ]
    ].head(15)
)

Rows with missing rank_diff: 27241

,date,window_days,rank,music_title,music_author,rank_diff,rank_diff_type,rank_diff_label
1,2024-05-23,7,2,Close,Cayo,NaN,4,new_to_top100
2,2024-05-23,7,3,Ghost Town,Kanye West,NaN,4,new_to_top100
3,2024-05-23,7,4,In My Mind,Lyn Lapid,NaN,4,new_to_top100
4,2024-05-23,7,5,Good Old Days,Macklemore & Kesha,NaN,4,new_to_top100
5,2024-05-23,7,6,No Mastico Culebras,Los Chavalitos,NaN,4,new_to_top100
7,2024-05-23,7,8,Hate Being Alone,Kodak Black,NaN,4,new_to_top100
8,2024-05-23,7,9,rock your hips,310babii & OhGeesy & BlueBucksClan,NaN,4,new_to_top100
9,2024-05-23,7,10,Where'd All the Time Go?,Dr. Dog,NaN,4,new_to_top100
10,2024-05-23,7,11,Spin Your Block,Clepto Maniack,NaN,4,new_to_top100
11,2024-05-23,7,12,Espresso,Sabrina Carpenter,NaN,4,new_to_top100
12,2024-05-23,7,13,Pink Matter,Frank Ocean,NaN,4,new_to_top100
13,2024-05-23,7,14,Close,Cayo,NaN,4,new_to_top100
18,2024-05-23,7,19,Big Energy (Originally Performed by Latto) [In...,Hit The Button Karaoke,NaN,4,new_to_top100
19,2024-05-23,7,20,Let's Go,JAXSON GAMBLE,NaN,4,new_to_top100
20,2024-05-23,7,21,BOA,Megan Thee Stallion,NaN,4,new_to_top100

In [89]:
duplicate_song_records = tiktok_trends.duplicated(
    subset=["date", "window_days", "song_id"],
    keep=False
)

print("Rows involved in repeated song records:",duplicate_song_records.sum())

display(
    tiktok_trends.loc[
        duplicate_song_records,
        ["date", "window_days", "song_id",
         "music_title", "rank", "clip_id"]
    ].head(20)
)

Rows involved in repeated song records: 4

,date,window_days,song_id,music_title,rank,clip_id
8963,2024-06-23,30,7378930449743710209,DEVIL IS A LIE,37,7378961993934407696
8964,2024-06-23,30,6886371996498675713,Mission Impossible (Funny Theme Remix),38,6886372003188574209
8969,2024-06-23,30,7378930449743710209,DEVIL IS A LIE,43,7378961993934407696
8973,2024-06-23,30,6886371996498675713,Mission Impossible (Funny Theme Remix),47,6886372003188574209

In [90]:
tiktok_7day = tiktok_trends[tiktok_trends["window_days"] == 7]

print("7-day dataset shape:", tiktok_7day.shape)
print("Unique songs:", tiktok_7day["song_id"].nunique())

print("\nRank statistics:")
display(tiktok_7day["rank"].describe())

print("\nRecords per date:")
display(tiktok_7day.groupby("date").size().describe())

7-day dataset shape: (35602, 14)
Unique songs: 10509

Rank statistics:

count    35602.000000
mean        50.510028
std         28.878160
min          1.000000
25%         25.000000
50%         51.000000
75%         76.000000
max        100.000000
Name: rank, dtype: float64

Records per date:

count    358.000000
mean      99.446927
std        0.756839
min       96.000000
25%       99.000000
50%      100.000000
75%      100.000000
max      100.000000
dtype: float64

In [91]:

# Check the date ranges of both datasets
print("Billboard date range:")
print(billboard["Date"].min(), "to", billboard["Date"].max())

print("\nTikTok 7-day date range:")
print(tiktok_7day["date"].min(), "to", tiktok_7day["date"].max())

# Compare the overall date ranges
overlap_start = max(billboard["Date"].min(),tiktok_7day["date"].min())

overlap_end = min(billboard["Date"].max(),tiktok_7day["date"].max())

print("\nOverlapping period:")
print(overlap_start, "to", overlap_end)

# Count Billboard records within that period
billboard_overlap = billboard[billboard["Date"].between(overlap_start, overlap_end)]

print("\nBillboard rows during the overlapping period:",len(billboard_overlap))

print("Billboard chart dates during the overlapping period:",billboard_overlap["Date"].nunique())

Billboard date range:
1958-07-30 00:00:00 to 2026-09-30 00:00:00

TikTok 7-day date range:
2024-05-23 00:00:00 to 2025-07-09 00:00:00

Overlapping period:
2024-05-23 00:00:00 to 2025-07-09 00:00:00

Billboard rows during the overlapping period: 5900
Billboard chart dates during the overlapping period: 59